### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BKSalman** [BKSalman/mouse_tracker#1]
- [x] replace enigo with rdev (for better cross-platform compatibility)
- [x] add RON file and read from it to enable users configuration
- [x] configurations/settings hot reload ( runtime reload )
- [ ] UI for editing settings
- [ ] make a read me file for the app on release
